version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql  
  redis:
    image: redis:3.0.5
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    tty: true
    stdin_open: true
    volumes:
      - .:/webapp:cached
volumes:
  db:
  redis: